# Delegate further configuration to subtasks
# placed in this same directory.

- include: install.yml
- include: configure.yml

- name: Ensure supervisord is running
  become: yes
  service:
    name: "supervisor"
    state: restarted