---
- name: get storm artifact
  get_url: >
    url={{storm_artifact_url}}
    dest={{packages_root}}
    use_proxy=no
    mode=644
    owner={{ansible_ssh_user}}

- name: install storm 
  shell: unzip {{packages_root}}/storm-0.8.1.zip creates={{packages_root}}/storm-{{storm_version}}

- name: create a link to the storm install dir
  file: >
    src={{packages_root}}/storm-{{storm_version}} 
    dest={{ansible_env.HOME}}/{{storm_name}} 
    state=link
    owner={{ansible_ssh_user}}
    mode=755

- name: add storm executable on the path
  lineinfile: >
    dest={{ansible_env.HOME}}/.bashrc
    state=present
    regexp='export PATH={{ansible_env.HOME}}/nimbus*'
    line='export PATH={{ansible_env.HOME}}/nimbus/bin:$PATH'


- name: create local storage dir for nimbus
  file: path={{ansible_env.HOME}}/storm_local state=directory mode=755 owner={{ansible_ssh_user}}

- name: setup storm config yml file
  template: src=storm.yml mode=644 dest={{ansible_env.HOME}}/nimbus/conf/storm.yaml

- include: zeromq.yml
