---
- name: download the zero mq artifact
  get_url: >
    url={{zeromq_artifact_url}}
    dest={{packages_root}}
    use_proxy=no
    mode=644
    owner={{ansible_ssh_user}}

- name: unzip zero mq artifact
  shell: tar -xf {{packages_root}}/{{zeromq_artifact}} creates={{packages_root}}/zeromq-{{zeromq_version}}

- name: install zero mq
  shell: ./configure --prefix={{packages_root}}/lib/zeromq; make; make install chdir={{packages_root}}/zeromq-{{zeromq_version}} creates={{packages_root}}/lib/zeromq

- name: download the java zero mq binding artifact
  git: repo={{jzmq_git_url}} dest={{packages_root}}/jzmq-{{jzmq_version}}

- name: install jzmq 
  shell: ./autogen.sh; ./configure --prefix={{packages_root}}/lib/jzmq --with-zeromq={{packages_root}}/lib/zeromq; make; make install chdir={{packages_root}}/jzmq-{{jzmq_version}} creates={{packages_root}}/lib/jzmq

