---
- name: download the zero mq artifact
  get_url: >
    url={{zeromq_artifact_url}}
    dest={{ansible_env.HOME}}
    use_proxy=no
    mode=644
    owner={{ansible_ssh_user}}

- name: unzip zero mq artifact
  shell: tar -xf {{zeromq_artifact}} creates=~/zeromq-{{zeromq_version}}

- name: install zero mq
  shell: ./configure --prefix={{ansible_env.HOME}}/zeromq; make; make install chdir=~/zeromq-{{zeromq_version}} creates=~/zeromq

- name: download the java zero mq binding artifact
  git: repo={{jzmq_git_url}} dest={{ansible_env.HOME}}/jzmq-{{jzmq_version}}

- name: install jzmq 
  shell: ./autogen.sh; ./configure --prefix={{ansible_env.HOME}}/jzmq --with-zeromq={{ansible_env.HOME}}/zeromq; make; make install chdir=~/jzmq-{{jzmq_version}} creates=~/jzmq

