---
- hosts: dev_machine
  remote_user: vagrant
  sudo: False

  roles:
      - { role: ansiblebit.oracle-java,
          oracle_java_set_as_default: yes,
          oracle_java_versio: 8 }
      - dev_box
