---
- hosts: nimbus_servers
  remote_user: vagrant

  roles:
    - { role: ansiblebit.oracle-java,
        oracle_java_set_as_default: yes}
    - common
    - storm
    - supervisord
    - {role: supervisor-config, 
       supervisor_program: "stormUI",
       supervisor_command: "storm ui"}
    - {role: supervisor-config, 
       supervisor_program: "nimbus",
       supervisor_command: "storm nimbus"}
       
  post_tasks:
    - name: start nimbus server
      supervisorctl: name=nimbus state=present
      become: yes
    - name: start storm ui server
      supervisorctl: name=stormUI state=present
      become: yes