---
- hosts: nimbus_servers
  remote_user: vagrant
  sudo: False

  roles:
    - common
    - storm
    - supervisord

  post_tasks:
    - name: start supervisor daemon
      shell: supervisord creates=/tmp/supervisor.sock
    - name: start nimbus server
      supervisorctl: name=nimbus state=present
