---
- hosts: nimbus_servers
  remote_user: vagrant
  sudo: False

  roles:
    - common
    - storm

  post_tasks:
  - name: start nimbus server
    shell: "storm nimbus &"

  - name: start UI  server
    shell: "storm ui &"
