---
- hosts: supervisor_servers
  remote_user: vagrant
  sudo: False

  roles:
    - common
    - storm
    - supervisord

  post_tasks:
    - name: start supervisor daemon
      shell: supervisord creates=/tmp/supervisor.sock
    - name: start supervisor server
      supervisorctl: name=supervisor state=present

