---
- hosts: supervisor_servers
  remote_user: vagrant
  vars:
    hosts_ips:
      - { name: 'nimbus', ip: '192.168.33.10' }
      - { name: 'zookeeper', ip: '192.168.33.11' }
  
  roles:
    - { role: ansiblebit.oracle-java,
        oracle_java_set_as_default: yes,
        oracle_java_versio: 8 }
    - common    
    
    - storm

    - supervisord
    - {role: supervisor-config, 
       supervisor_program: "supervisor",
       supervisor_command: "storm supervisor",
       supervisor_user: "storm" }

  post_tasks:
    - name: start supervisor server
      supervisorctl: name=supervisor state=present
      become: yes
