---
- hosts: supervisor_servers
  remote_user: vagrant

  roles:
    - { role: ansiblebit.oracle-java,
        oracle_java_set_as_default: yes,
        oracle_java_versio: 8 }
    - common    
    - storm
    - supervisord
    - {role: supervisor-config, 
       supervisor_program: "supervisor",
       supervisor_command: "storm supervisor"}

  post_tasks:
    - name: start supervisor server
      supervisorctl: name=supervisor state=present
      become: yes
