---
- hosts: supervisor_servers
  remote_user: vagrant

  roles:
    - { role: ansiblebit.oracle-java,
        oracle_java_set_as_default: yes,
        oracle_java_versio: 8 }
    - common    
    - storm
    - supervisord

  post_tasks:
    - name: start supervisor server
      supervisorctl: name=supervisor state=present
      become: yes
