---
- hosts: zookeeper_servers
  remote_user: vagrant
  sudo: False

  roles:
    - common
    - zookeeper
    - supervisord

  post_tasks:
    - name: start supervisor daemon
      shell: supervisord creates=/tmp/supervisor.sock
    - name: start zookeeper server
      supervisorctl: name=zookeeper state=present
