---
- name: set java heap size to a max of 3GB
  lineinfile: >
    dest={{ansible_env.HOME}}/.bashrc
    regexp='export JAVA_OPTS=.*'
    line='export JAVA_OPTS="-Xms1g -Xmx3g"'
    state=present

- name: Creates directory
  file: path={{ansible_env.HOME}}/packages state=directory    

- apt: name=zookeeperd
  become: yes

- name: upload configuration file
  template: src=zoo.cfg dest=/etc/zookeeper/conf/zoo.cfg mode=644
  become: yes

# - name: create zookeeper data directory
  # file: state=directory path={{zookeeper_data_dir}} mode=755 owner={{ansible_ssh_user}}

- name: upload myid file
  template: src=myid dest=/etc/zookeeper/conf/myid mode=644
  become: yes